version: '3.9'

services:
  purr:
    build:
      dockerfile: docker/Dockerfile
      context: .
    restart: 'no'
    tty: true # Colorize logs
    env_file:
      - ./.env
    environment:
      NODE_ENV: development
    volumes:
      - ./:/app
      - node_home:/home/node

volumes:
  node_home:
