version: '3.9'

services:
  worker:
    build:
      dockerfile: docker/Dockerfile
      context: .
    command:
      - 'worker check'
    environment:
      NODE_ENV: development
    volumes:
      - ./:/app
      - node_home:/home/node

  server:
    build:
      dockerfile: docker/Dockerfile
      context: .
    command:
      - 'server start'
    environment:
      NODE_ENV: development
      # DEBUG: http,express:*
    volumes:
      - ./:/app
      - node_home:/home/node
    labels:
      - traefik.enable=true
      - traefik.http.routers.purr.rule=Host(`purr.traefik.lcl`)

volumes:
  node_home:
